# Workflow to try and run UI selenium tests

name: UI-Regression DRAFT

on:
  schedule:
    - cron: '30	18	*	*	*'
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.3.0
        with:
          chrome-version: stable
      - run: yarn install     
      - run: yarn ui-regression
